name: Deploy to VPS

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_SSH_HOST }}
          REMOTE_USER: ${{ secrets.VPS_SSH_USER }}
          SOURCE: "./"
          TARGET: "/home/dev/playground/playground-api/source"
          EXCLUDE: "/dist/, /node_modules/"

      - name: Run post-deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/dev/playground/playground-api/source
            npm install --production
            /home/dev/.nvm/versions/node/v20.17.0/bin/pm2 restart playground-api